# Generated by Django 5.1.2 on 2024-10-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
