# Generated by Django 5.1.2 on 2024-10-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_updated",
        ),
    ]
