# Generated by Django 5.1.2 on 2024-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_discount_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
